#include "encoding/BooleanDecoder.hpp"
#include "encoding/PlainDecoder.hpp"
#include "encoding/PlainByteArrayDecoder.hpp"
#include "encoding/PlainDictionaryDecoder.hpp"
#include "encoding/RleDecoder.hpp"
